# This case study consists of 1000 marks and the solution file is expected to be submitted in the upcoming session for evaluation.

In [1]:
import numpy as np

### 1.Create two matrices of 3*3 and perform the arithmatic operations metioned in below "print" statements

In [20]:
mat1 = np.arange(9).reshape(3,3)
mat2 = np.arange(9,18).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)


print("\nDivision\n------------------\n", mat1/mat2)
print("\nLinear combination: 3*A - 2*B\n-----------------------------\n", 3*mat1 - 2*mat2)


print("\nAddition of a scalar (100)\n-------------------------\n", mat1+100)


print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, mat1 sq-root using pow function\n-------------------------------------------\n",np.sqrt(mat1))


1st Matrix of random single-digit numbers
----------------------------------------
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[ 9 10 11]
 [12 13 14]
 [15 16 17]]

Addition
------------------
 [[ 9 11 13]
 [15 17 19]
 [21 23 25]]

Multiplication
------------------
 [[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]

Division
------------------
 [[0.         0.1        0.18181818]
 [0.25       0.30769231 0.35714286]
 [0.4        0.4375     0.47058824]]

Linear combination: 3*A - 2*B
-----------------------------
 [[-18 -17 -16]
 [-15 -14 -13]
 [-12 -11 -10]]

Addition of a scalar (100)
-------------------------
 [[100 101 102]
 [103 104 105]
 [106 107 108]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  0   1   8]
 [ 27  64 125]
 [216 343 512]]

Exponentiation, mat1 sq-root using pow function
-------------------------------------------
 [[0.         1.         1.41421356]
 [1.73205081 2.

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

### 2.Create two 3 * 3 matrices and perform the following operations as describe in print statement.

In [21]:
from numpy.random import randint as ri

In [43]:
from numpy.random import randint as ri
mat1 = np.matrix(ri(1,100,(3,3)))
mat2 = np.matrix(ri(1,100,(3,3)))
print("\n1st Matrix of random single-digit numbers\n","-"*50,"\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n","-"*50,"\n",mat2)


print("\nSum of all numbers in 1st matrix\n","-"*50,"\n",np.sum(mat1))
print("\nSum of all numbers in columns of 1st matrix\n","-"*50,"\n",mat1.sum(axis=0))


print("\nSum of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1.sum(axis=1))
print("\nProduct of all numbers in rows of 1st matrix\n","-"*50,"\n",mat1.prod(axis=1))


print("\nProduct of all numbers in columns of 2nd matrix\n","-"*50,"\n",mat2.prod(axis=0))
print("\nMean of all numbers in 1st matrix\n","-"*50,"\n",mat1.mean())


print("\nStandard deviation of all numbers in 1st matrix\n","-"*50,"\n",mat1.std())


mat1 = np.matrix(ri(1,99,(3,3)))
print("\nModified matrix of random numbers from 1 to 99\n","-"*50,"\n",mat1)


print("\nStandard deviation of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.std())


print("\nVariance of all numbers in the modified matrix, a larger number\n","-"*80,"\n",mat1.var())


print("\nMedian of all numbers in the modified matrix\n","-"*60,"\n",np.median(mat1))



1st Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[13 15 38]
 [31 26 13]
 [19 91 90]]

2nd Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[ 6 60 50]
 [17 64 83]
 [79 18 16]]

Sum of all numbers in 1st matrix
 -------------------------------------------------- 
 336

Sum of all numbers in columns of 1st matrix
 -------------------------------------------------- 
 [[ 63 132 141]]

Sum of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [[ 66]
 [ 70]
 [200]]

Product of all numbers in rows of 1st matrix
 -------------------------------------------------- 
 [[  7410]
 [ 10478]
 [155610]]

Product of all numbers in columns of 2nd matrix
 -------------------------------------------------- 
 [[ 8058 69120 66400]]

Mean of all numbers in 1st matrix
 -------------------------------------------------- 
 37.333333333333336

Standard deviation of all numbers in 1st m

###  3.Create a 3 \* 3 Matrix and Modify its shape to 9\*1 matrix.

In [54]:
##Solution
mat1 = np.matrix(ri(1,100,(3,3)))
print("\n1st Matrix of shape 3*3 \n","-"*50,"\n",mat1)

print("\n1st Modified matrix to shape 9*1 \n","-"*50,"\n",mat1.reshape(9,1))


1st Matrix of shape 3*3 
 -------------------------------------------------- 
 [[39 69 41]
 [ 1 67 98]
 [41 44 33]]

1st Modified matrix to shape 9*1 
 -------------------------------------------------- 
 [[39]
 [69]
 [41]
 [ 1]
 [67]
 [98]
 [41]
 [44]
 [33]]


### 4.Sort

In [60]:
A = ri(1,100,5) # Vector of random interegrs
print("\nVector of 10 random integers from 1 to 100\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))



Vector of 10 random integers from 1 to 100
 -------------------------------------------------- 
 [92  5 73 56 66]

Here is the sorted vector
 -------------------------------------------------- 
 [ 5 56 66 73 92]


In [84]:
M = ri(1,100,(5,5)) #  5*5 Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n", np.sort(M, axis=1)) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n", np.sort(M, axis=0))


5x5 Matrix of random integers
 -------------------------------------------------- 
 [[56 63 62 39 64]
 [24 24  7 34  1]
 [73 30 15 15 37]
 [62 65 17 54 68]
 [93 62 57 87 78]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[39 56 62 63 64]
 [ 1  7 24 24 34]
 [15 15 30 37 73]
 [17 54 62 65 68]
 [57 62 78 87 93]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[24 24  7 15  1]
 [56 30 15 34 37]
 [62 62 17 39 64]
 [73 63 57 54 68]
 [93 65 62 87 78]]


### 5.Create a,b,c  10 element vectors of random integers and perform the respective operation mentioned in print statement

In [90]:
# Fill the following ***** with appropriate solution.
a=ri(1,10,5)
b=ri(11,20,5)
c=ri(21,30,5)

print("a:", a)
print("b:", b)
print("c:", c)

print("Max of a:", np.max(a))
print("Max of b:",np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))

print("Max of a:", np.max(a))
print("Max of b:", np.max(b))


print("Max of a location:", np.argmax(a))
print("Max of b location:", np.argmax(b))
print("Max of c location:", np.argmax(c))



a: [8 6 8 9 5]
b: [14 16 19 14 17]
c: [26 26 22 21 21]
Max of a: 9
Max of b: 19
Max of a location: 3
Max of b location: 2
Max of c location: 0
Max of a: 9
Max of b: 19
Max of a location: 3
Max of b location: 2
Max of c location: 0


## Universal functions

6. Create 3*3 matrices of random single-digit numbers.<br/>
Apply universal functions on it. (square root,exponetial,log10,Modulo etc.)

In [97]:

mat1 = np.matrix(ri(1,10,(3,3)))
mat2 = np.matrix(ri(11,20,(3,3)))
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat1))


print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.power(mat1,2))


print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))


print("\nModulo reminder using np\n",'-'*50,"\n", np.mod(mat2,mat1))



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 1 6]
 [6 6 8]
 [7 7 4]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[19 11 16]
 [17 11 15]
 [14 13 15]]

Sq-root of 1st matrix using np
------------------
 [[1.73205081 1.         2.44948974]
 [2.44948974 2.44948974 2.82842712]
 [2.64575131 2.64575131 2.        ]]

Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[ 9  1 36]
 [36 36 64]
 [49 49 16]]

10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.47712125 0.         0.77815125]
 [0.77815125 0.77815125 0.90308999]
 [0.84509804 0.84509804 0.60205999]]

Modulo reminder using np
 -------------------------------------------------- 
 [[1 0 4]
 [5 5 7]
 [0 6 3]]


### 7.Generating matrices from distributions

In [98]:
np.random.uniform(0,1,(2,3))

array([[0.13355567, 0.87815704, 0.02145331],
       [0.07071353, 0.49342789, 0.37242453]])

In [108]:
np.random.multinomial(20, [1/6.]*6, size=1)

array([[4, 5, 1, 3, 3, 4]])

In [110]:

print("\nRandom number generation (from Uniform distribution)\n")
print(np.random.uniform(0,1,(2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

print("\nNumbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal\n")
print(np.random.standard_normal(4))

print("\nRandom integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(2,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)

print("\n20 samples drawn from a dice throw:",np.random.multinomial(20, [1/6.]*6, size=1)) # 20 samples drawn from a dice throw


Random number generation (from Uniform distribution)

[[0.45241205 0.59092369 0.04372337]
 [0.12995701 0.08004857 0.80575622]]

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal

[ 1.53327573 -0.4195154   0.42082301  0.7323684 ]

Random integer vector: [19  6  4 16 59 38 49 66 42 22]

Random integer matrix
[[43 69 76  9]
 [25 19 31 65]]

20 samples drawn from a dice throw: [[3 5 3 5 1 3]]


### 8.Find the nearest value from a given number in an array using NumPy.

In [21]:
#Steps
#Create an array of 5 random element from 1 to 12
#Suppose find the nearest values of 10 in an array so set value=10
#find the index where difference is minimum and get the element

4.859577122593637


In [138]:
arr = ri(1,12,5)
print(arr)
res = 10-arr
print(res)
print("\n Index where difference is minimum", res.argmin())
print("\n Element where difference is minimum", arr[res.argmin()])

[9 4 4 2 7]
[1 6 6 8 3]

 Index where difference is minimum 0

 Element where difference is minimum 9


### 9.Write code using numpy to produce following output
[[0 0 0] [0 1 2] [0 2 4]]

In [139]:
mat = np.matrix('0 0 0; 0 1 2; 0 2 4')
mat

matrix([[0, 0, 0],
        [0, 1, 2],
        [0, 2, 4]])